### PR TITLE
Add PHP 7.2 into the mix

### PR DESCRIPTION
**Pull request by raphaelstolt**
Added PHP 7.2 support and also eased the AppVeyor configuration. Both for the generated configuration files as well for the own repository configurations.

### CODE REVIEW

**Comment by raphaelstolt** [comment]
Currently the Travis CI [build](https://travis-ci.org/jonathantorres/construct/jobs/286720472) for `7.2` fails due to errors raised in the `phpunit/phpunit` and `mockery/mockery` dependencies. 

If Composer would install them in `^6.0` and `^1.0` this problem should be solved; not quite sure how to achieve this.

**Comment by jonathantorres** [comment]
Maybe allow the build to fail on travis until php 7.2 is released?

**Comment by raphaelstolt** [comment]
That would make the build green; but we're still having a dependency problem. Builds against e.g. `7.0` should also use `phpunit/phpunit:^6.0` and `mockery/mockery:^1.0`; which doesn't happen currently.

Maybe we should introduce version branches like described [here](https://github.com/composer/composer/issues/4090)?

**Comment by jonathantorres** [comment]
I see, what is your recommendation? to create an `1.*` branch and then bump to `2.0` which will be in the `master` branch?

**Comment by raphaelstolt** [comment]
Yes we should create a `1.*` branch which should include support for PHP `5.6` up to `7.2` which is allowed to fail builds for `7.2` and lives until `5.6` goes EOL (31 Dec 2018). Than we should create a `2.*` branch which should only support `7.*` versions and might become the new `master` branch. 

Not quite sure if new features added in the `2.*` branch should also go into the `1.*` branch because this will require some extra work. This decision is entirely up to you. 😇

Also related to this is issue #211, for which I could send a PR later today.

**Comment by jonathantorres** [comment]
Sounds good!

- I'll create the `1.*` branch for the next release (which will be 1.6). This one will support php `5.6` and later. But no new features will be added here, only bugfixes/patches.
- The `master` branch will hold the next mayor version (2.0), this one will support php `7.0` and later. New features should be submitted here.
- If somebody complains (don't think that would happen) about the removal of php `5.4` and `5.5`, I don't mind adding support for it on the `1.*` branch.

Let me know your thoughts, thanks again!

**Pull request merged**
