### PR TITLE
Enforce coding standards.

### PR DESCRIPTION
**Pull request by raphaelstolt**
Adds a local php-cs-fixer cache and validation during Travis CI builds.

### CODE REVIEW

**Comment by localheinz** [comment]
Unfortunately, the caching doesn't work on Travis, but if you dare to use [`friendsofphp/php-cs-fixer:v2.0.0-alpha`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.0.0-alpha), then you can make use of it on Travis, too!

This significantly speeds up build times.

For an example, take a look at https://github.com/refinery29/php-cs-fixer-config/blob/master/.php_cs!

We have been using it for a while, it works fine.

On a separate note, I can't wait for `2.0.0` release of `friendsofphp-php-cs-fixer`!

😄 

For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1076.

**Comment by raphaelstolt** [comment]
@localheinz Thanks for the heads-up. I guess we wait for the `2.0.0` release of `friendsofphp-php-cs-fixer`, or @jonathantorres should we go experimentell?

**Comment by jonathantorres** [comment]
I wouldn't mind using the alpha version on the construct codebase itself. For the generated project we should use the `2.0.0` release.

**Comment by raphaelstolt** [comment]
Done with #151. We should prolly create a backlog issue to update the generated project artifacts once `2.0.0` is released.

**Pull request merged**
